nginx:
    build: nginx
    links:
        - fusiondirectory
    ports:
        - "80:80"
    volumes:
        - nginx/config/sites-enabled:/etc/nginx/sites-enabled
        - nginx/data/www:/var/www
openldap:
    build: openldap
    ports:
        - "127.0.0.1:389:389"
fusiondirectory:
    build: fusiondirectory
    links:
        - openldap
    volumes:
        - fusiondirectory/config/sites-enabled:/etc/apache2/sites-enabled
        - fusiondirectory/config/fusiondirectory:/etc/fusiondirectory
    ports:
        - "127.0.0.1:8080:80"
postgres:
    build: postgres
    ports:
        - "127.0.0.1:5432:5432"
redis:
    build: redis
    volumes:
        - redis/config/:/redis_conf
    ports:
        - "127.0.0.1:6379:6379"
